import os

working_dir = "D:\\anime\\[Kusonime] A Lull in the Sea BD 720P" #TODO: a pop up browse window to choose a directory

extensions = [ # Generated by ChatGPT
    ".mp3", ".aac", ".wav", ".flac", ".alac", ".ogg", ".wma", ".aiff",
    ".opus", ".m4a", ".amr", ".mid", ".midi", ".pcm", ".dsd", ".ape",
    ".mka", ".ra", ".vox", ".tta", ".mp4", ".mkv", 
    ".avi", ".mov", ".wmv", ".flv", ".webm", ".mpeg",
    ".mpg", ".m4v", ".3gp", ".3g2", ".mts", ".m2ts", ".ts", ".vob",
    ".ogv", ".rm", ".rmvb", ".divx", ".f4v", ".asf", ".amv", ".dav"
]


def file_list():
    """
    return a list of file in the working directory
    TODO: sort the files in alphabetical order
    """
    os.chdir(working_dir)
    file_list = os.listdir() # Gets a list of files in the CWD

    for index, file_name in enumerate(file_list, start=1):
        print(index, file_name) # Print the file with a number
    
    return file_list

def get_extension(filename):
    lasts_characters = filename[-4:]
    for ext in extensions:
        if ext in lasts_characters:
            return ext
            break

def rename(old_filename, new_name):
    """
    accepts old filename, and changes it to the specified new filename
    """
    try:
        os.rename(old_filename, new_name)
        print(f"Renamed '{old_filename}' to '{new_name}'")

    except FileNotFoundError:
        print(f"Error: 'file {old_filename}' does not exist")

    except PermissionError:
        print(f"Error: Permission denied to rename '{old_filename}'")

    except Exception as e:
        print(f"Error: {e}")

def number_location_prefix(num_location):

    if num_location == 1:
        return "{index} - {new_name}"
    
    elif num_location == 2:
        return "{new_name} - {index}"

    elif num_location == 3:
        return "{index} {new_name}"

    elif num_location == 4:
        return "{new_name} {index}"

    else :
        return "{new_name}"


def mainloop():
    """
    mainloop of the program
    """
    looping = True
    command = "" # the command variable

    while looping:
        command = input("Enter a Command : ")
        if command == "1": # Gets a file list and input a file number
            
            file_list()

        elif command == "2": # Single file rename
            
            files = file_list()
            print("Choose a file using a number (ex= 1)")
            file_number = int(input("Enter a number : "))

            new_filename = input("Enter a new name : ")
            extension = str(get_extension(files[file_number]))

            rename(files[file_number], new_filename + extension)

        elif command == "3": # Bulk rename
            
            files = file_list()
            
            new_filename = input("Enter a new name : ")
            extension = str(get_extension(files[2]))

            for index, file in enumerate(files, start=1):
                rename((str(file)), (new_filename + " " + str(index) + extension))
            
        elif command == "4": # exit
            
            print("Bye Bye :)")
            looping = False
            break

mainloop()